"""Process FC matrices generated by micapipe and store QC metadata."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List

import nibabel as nib
import numpy as np
import pandas as pd
from brainspace.mesh.mesh_io import read_surface
from brainspace.plotting import plot_hemispheres
from joblib import Parallel, delayed
from nilearn import surface


@dataclass(frozen=True)
class FCConfig:
    """Reusable configuration for FC processing."""

    home_dir: Path = Path("/public/home/baishw/WMH_MCI")
    atlas_nodes: int = 200
    fd_mean_threshold: float = 0.5
    fd_max_threshold: float = 10.0
    fd_length_threshold: int = 200
    threads: int = -1

    @property
    def atlas_name(self) -> str:
        return f"schaefer-{self.atlas_nodes}"

    @property
    def data_dir(self) -> Path:
        return self.home_dir / "data"

    @property
    def mica_out_dir(self) -> Path:
        return self.home_dir / "mica_out" / "micapipe_v0.2.0"

    @property
    def freesurfer_dir(self) -> Path:
        return self.home_dir / "mica_out" / "freesurfer"

    @property
    def fc_output_dir(self) -> Path:
        return self.data_dir / "fcs_raw"

    @property
    def qc_fd_dir(self) -> Path:
        return self.home_dir / "qc" / "fmri"

    @property
    def qc_snr_dir(self) -> Path:
        return self.home_dir / "qc" / "SNR"
    @property
    def log_path(self) -> Path:
        return self.home_dir / "qc" / "proc_fc_log.csv"


def ensure_directories(paths: Iterable[Path]) -> None:
    """Create directories if they do not already exist."""
    for directory in paths:
        directory.mkdir(parents=True, exist_ok=True)


def purge_directory(directory: Path) -> None:
    """Delete all .npy files in the specified directory."""
    if not directory.exists():
        return
    for entry in directory.glob("*.npy"):
        entry.unlink()


def plot_snr(sub_id: str, func_dir: Path, config: FCConfig) -> None:
    """Generate and save tSNR surface plots for QC purposes."""
    snr_path = func_dir / "volumetric" / f"{sub_id}_space-func_desc-se_tSNR.shape.gii"
    if not snr_path.exists():
        print(f"[Warn] Missing tSNR data for {sub_id}", flush=True)
        return

    snr_data = surface.load_surf_data(str(snr_path))
    lh_path = config.freesurfer_dir / sub_id / "surf" / "lh.inflated"
    rh_path = config.freesurfer_dir / sub_id / "surf" / "rh.inflated"
    if not (lh_path.exists() and rh_path.exists()):
        print(f"[Warn] Missing inflated surfaces for {sub_id}", flush=True)
        return

    inflated_lh = read_surface(str(lh_path), itype="fs")
    inflated_rh = read_surface(str(rh_path), itype="fs")

    # Create output directory if it doesn't exist
    ensure_directories([config.qc_snr_dir])
    plot_hemispheres(
        inflated_lh,
        inflated_rh,
        array_name=snr_data,
        size=(800, 200),
        color_bar="bottom",
        zoom=1.25,
        embed_nb=True,
        interactive=False,
        share="both",
        cmap="inferno",
        transparent_bg=False,
        screenshot=True,
        filename=str(config.qc_snr_dir / f"{sub_id}.png"),
    )


def load_fc_matrix(fc_path: Path, atlas_nodes: int) -> np.ndarray:
    """Load the FC matrix from a GIFTI file and format it appropriately."""
    fc_mat = nib.load(str(fc_path)).darrays[0].data
    fc_mat = fc_mat[-atlas_nodes:, -atlas_nodes:]
    np.fill_diagonal(fc_mat, 1)
    return fc_mat


def load_fd_stats(fd_path: Path) -> tuple[float, float, int]:
    """Load framewise displacement statistics from a .1D file."""    
    if not fd_path.exists():
        return np.nan, np.nan, 0

    fd_values = np.loadtxt(fd_path)
    fd_values = np.atleast_1d(fd_values)
    if fd_values.size == 0:
        return np.nan, np.nan, 0

    mean_fd = float(np.mean(fd_values))
    max_fd = float(np.max(fd_values))
    length_fd = int(fd_values.size)
    return mean_fd, max_fd, length_fd


def passes_fd_thresholds(mean_fd: float, max_fd: float, frame_count: int, config: FCConfig) -> bool:
    """Check if the FD statistics pass the configured thresholds."""
    return (
        not np.isnan(mean_fd)
        and not np.isnan(max_fd)
        and mean_fd < config.fd_mean_threshold
        and max_fd < config.fd_max_threshold
        and frame_count > config.fd_length_threshold
    )


def symmetrize_fc(matrix: np.ndarray) -> np.ndarray:
    """Ensure the FC matrix is symmetric with ones on the diagonal."""
    symmetric = (matrix + matrix.T) / 2
    np.fill_diagonal(symmetric, 1)
    return symmetric


def copy_fd_qc_plot(fd_plot_path: Path, destination: Path) -> None:
    """Copy the FD QC plot to the designated QC directory."""
    if fd_plot_path.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(fd_plot_path, destination)


def par_proc_fc(sub_id: str, config: FCConfig) -> dict:
    """Process a single subject's FC data and return QC metrics."""
    func_dir = config.mica_out_dir / sub_id / "func" / "desc-se_dir-AP_rest_bold"
    surf_dir = func_dir / "surf"
    vol_dir = func_dir / "volumetric"

    if not surf_dir.exists():
        print(f"[Error] {sub_id}: missing surface directory", flush=True)
        return {
            "subject_id": sub_id,
            "status": 0,
            "mean_fd": np.nan,
            "max_fd": np.nan,
            "frame_count": 0,
        }

    fc_candidates = list(
        surf_dir.glob(f"{sub_id}*atlas-{config.atlas_name}_desc-FC.shape.gii")
    )
    if not fc_candidates:
        print(f"[Error] {sub_id}: FC file missing", flush=True)
        return {
            "subject_id": sub_id,
            "status": 0,
            "mean_fd": np.nan,
            "max_fd": np.nan,
            "frame_count": 0,
        }

    fc_matrix = load_fc_matrix(fc_candidates[0], config.atlas_nodes)
    fd_stats = load_fd_stats(vol_dir / f"{sub_id}_space-func_desc-se_metric_FD.1D")
    mean_fd, max_fd, frame_count = fd_stats

    if passes_fd_thresholds(mean_fd, max_fd, frame_count, config):
        fc_matrix = symmetrize_fc(fc_matrix)
        ensure_directories([config.fc_output_dir, config.qc_fd_dir])
        np.save(config.fc_output_dir / f"{sub_id}_fc-wb_{config.atlas_name}.npy", fc_matrix)
        copy_fd_qc_plot(
            vol_dir / f"{sub_id}_space-func_desc-se_framewiseDisplacement.png",
            config.qc_fd_dir / f"{sub_id}.png",
        )
        print(f"[Info] {sub_id} processed", flush=True)
        status = 1
    else:
        print(f"[Warn] {sub_id} failed FD QC", flush=True)
        status = 0

    return {
        "subject_id": sub_id,
        "status": status,
        "mean_fd": mean_fd,
        "max_fd": max_fd,
        "frame_count": frame_count,
    }


def main() -> None:
    """Main function to process FC matrices for all subjects."""
    config = FCConfig()
    print(f"Run {__file__} with atlas {config.atlas_name}", flush=True)

    ensure_directories([config.fc_output_dir, config.qc_fd_dir])
    purge_directory(config.fc_output_dir)

    if not config.mica_out_dir.exists():
        raise FileNotFoundError(f"MICA output directory missing: {config.mica_out_dir}")

    subjects = sorted(entry.name for entry in config.mica_out_dir.iterdir() if entry.is_dir())
    print(f"Total {len(subjects)} subjects to process.", flush=True)

    results = Parallel(n_jobs=config.threads)(
        delayed(par_proc_fc)(subject, config) for subject in subjects
    )

    df = pd.DataFrame(results)
    df.to_csv(config.log_path, index=False)


if __name__ == "__main__":
    main()
